# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/Users/tlenzi/Desktop/GLIB/amc_glib/trunk/glib_v3/fw/fpga/prj/ipbus_slave/PlanAhead/PlanAhead.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/Users/tlenzi/Desktop/GLIB/amc_glib/trunk/glib_v3/fw/fpga/src/system/ethernet/ipcore_dir/basex/coregen.cgc"

set ipFile "c:/Users/tlenzi/Desktop/GLIB/amc_glib/trunk/glib_v3/fw/fpga/src/system/ethernet/ipcore_dir/basex/v6_emac_v2_3_basex.xco"

set ipName "v6_emac_v2_3_basex"

set hdlType "VHDL"

set cgPartSpec "xc6vlx130t-1ff1156"

set chains "GENERATE_CURRENT_CHAIN"

set params ""

set bomFilePath "c:/Users/tlenzi/Desktop/GLIB/amc_glib/trunk/glib_v3/fw/fpga/src/system/ethernet/ipcore_dir/basex/pa_cg_bom.xml"

# generate the IP
set result [source "c:/Xilinx/14.7/ISE_DS/PlanAhead/scripts/pa_cg_gen_out_prods.tcl"]

exit $result

